/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.Controller;
import domain.Korisnik;
import domain.role.UlogaKorisnika;
import form.delo.FrmPregledDela;
import form.korisnik.FrmKorisnik;
import form.korisnik.FrmPregledKorisnika;
import form.kritika.FrmPregledKritika;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import session.Session;
import usecase.UseCase;

/**
 *
 * @author Phenom
 */
public class FrmMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavniProzor
     */
    public FrmMainMenu() {
        initComponents();
        fillForm();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKorisnik = new javax.swing.JLabel();
        btnKritika = new javax.swing.JButton();
        btnDelo = new javax.swing.JButton();
        btnKorisnik = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmProfil = new javax.swing.JMenu();
        jmiIzmeniProfil = new javax.swing.JMenuItem();
        jmiOdjaviSe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblKorisnik.setText("Dobrodosao/la: ");

        btnKritika.setText("Kritike");
        btnKritika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKritikaActionPerformed(evt);
            }
        });

        btnDelo.setText("Dela");
        btnDelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeloActionPerformed(evt);
            }
        });

        btnKorisnik.setText("Korisnici");
        btnKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKorisnikActionPerformed(evt);
            }
        });

        jmProfil.setText("Profil");

        jmiIzmeniProfil.setText("Izmeni profil");
        jmiIzmeniProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmeniProfilActionPerformed(evt);
            }
        });
        jmProfil.add(jmiIzmeniProfil);

        jmiOdjaviSe.setText("Odjava sa sistema");
        jmiOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOdjaviSeActionPerformed(evt);
            }
        });
        jmProfil.add(jmiOdjaviSe);

        jMenuBar1.add(jmProfil);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblKorisnik)
                .addGap(225, 225, 225))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnDelo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnKritika, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKorisnik)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKritika, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOdjaviSeActionPerformed
        try {
            odjaviSe();
        } catch (Exception ex) {
            Logger.getLogger(FrmMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiOdjaviSeActionPerformed

    private void jmiIzmeniProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmeniProfilActionPerformed
        Korisnik k = Session.getInstance().getKorisnik();
        Session.getInstance().getUseCaseParams().put("korisnik", k);
        JDialog frmIzmenaKorisnika = new FrmKorisnik(null, true,  FrmMode.EDIT, this);
        frmIzmenaKorisnika.setVisible(true);
    }//GEN-LAST:event_jmiIzmeniProfilActionPerformed

    private void btnKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKorisnikActionPerformed
        Session.getInstance().setCurrentUseCase(UseCase.UC_SEARCH_USER);
        JDialog frmPregledKorisnika = new FrmPregledKorisnika(this,true);
        frmPregledKorisnika.setVisible(true);
    }//GEN-LAST:event_btnKorisnikActionPerformed

    private void btnDeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeloActionPerformed
        JDialog frmPregledDela = new FrmPregledDela(this, true);
        frmPregledDela.setVisible(true);
    }//GEN-LAST:event_btnDeloActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            odjaviSe();
        } catch (Exception ex) {
            Logger.getLogger(FrmMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnKritikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKritikaActionPerformed
        JDialog frmKritike = new FrmPregledKritika(this, true, FrmMode.EDIT);
        frmKritike.setVisible(true);
    }//GEN-LAST:event_btnKritikaActionPerformed
    
    
    
    
    public javax.swing.JLabel getLblKorisnik(){
        return lblKorisnik;
    }
    
    private void centerAndFixForm() {
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelo;
    private javax.swing.JButton btnKorisnik;
    private javax.swing.JButton btnKritika;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmProfil;
    private javax.swing.JMenuItem jmiIzmeniProfil;
    private javax.swing.JMenuItem jmiOdjaviSe;
    private javax.swing.JLabel lblKorisnik;
    // End of variables declaration//GEN-END:variables

    private void fillForm() {
        centerAndFixForm();
        fillUser();
        
        switch(Session.getInstance().getKorisnik().getAdminRole()) {
            case UlogaKorisnika.ADMIN:
                btnKritika.setVisible(true);
                
                break;
                
            case UlogaKorisnika.USER:
                btnKritika.setVisible(false);
                break;
        }
    }

    private void fillUser() {
        lblKorisnik.setText("Dobrodosao/la " + Session.getInstance().getKorisnik().toString());
    }

    private void odjaviSe() throws Exception{
        Controller.getInstance().logout(Session.getInstance().getKorisnik());
        this.dispose();
        Session.getInstance().setKorisnik(null);
        JFrame frmLogin = new FrmLogIn();
        frmLogin.setVisible(true);
    }
}
